Initialize walrus/sljit submodule in pr_ci build
Commit e799fc311 replaced --recursive with explicit submodule
init but missed walrus's nested sljit dependency, causing:

  fatal error: sljitLir.h: No such file or directory

Add one more level of init for walrus/third_party/sljit.

Signed-off-by: Boram Bae <boram21.bae@samsung.com>